<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>adls</string>
		<string>bmm</string>
	</array>
	<key>name</key>
	<string>ODIN</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--\s*.+)$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(\w+)\s+=</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+([\w\-.]+)</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s+\[([\w\-.]+)\]</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s+([\w\d]+)\s+=</string>
			<key>name</key>
			<string>entity</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>&lt;\[(.+)\]&gt;</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[(\w\w\d.+)\]</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>"(\w\w\d.+)"</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((.+)\)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>&lt;(\w+)&gt;</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>&lt;\|(.+)\|&gt;</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{(.+)\}</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.literal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>"(.+)"</string>
			<key>name</key>
			<string>string.literal</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.odin</string>
	<key>uuid</key>
	<string>70d8d002-ea2b-476c-8246-cc6ab1b46d68</string>
</dict>
</plist>
